package UdpClient;

import UdpClient.Runner;

import javax.swing.*;
import java.awt.*;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;

public class ChatApp {

    private InetAddress ipAddress;
    private int port;

    private DatagramPacket createPacket(String message, InetAddress ipAddress, int port) {
        var sendData = message.getBytes();
        return new DatagramPacket(sendData, sendData.length, ipAddress, port);
    }

    public ChatApp() throws Exception {
        this.socket = new DatagramSocket();
        this.ipAddress = InetAddress.getByName("localhost");
        this.port = 9876;
        JFrame frame = new JFrame("ChatApp");
        frame.setContentPane(this.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        new Runner(this.chatTextArea, this.socket).start();
        registerButton.addActionListener(e -> {
            var username = inputTextField.getText();
            var request = "/rg" + username;
            var sendPacket = createPacket(request, this.ipAddress, this.port);
            try {
                this.socket.send(sendPacket);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
        sendButton.addActionListener(e -> {
            var message = this.inputTextField.getText();
            var sendPacket = createPacket(message, this.ipAddress, this.port);
            try {
                this.socket.send(sendPacket);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
    }

    private JPanel mainPanel;
    private JTextField inputTextField;
    public JTextArea chatTextArea;
    private JButton registerButton;
    private JButton sendButton;
    private JLabel usernameLabel;
    public DatagramSocket socket;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(500, 250));
        mainPanel.setPreferredSize(new Dimension(500, 250));
        chatTextArea = new JTextArea();
        chatTextArea.setPreferredSize(new Dimension(200, 75));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(chatTextArea, gbc);
        registerButton = new JButton();
        registerButton.setText("Register");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(registerButton, gbc);
        sendButton = new JButton();
        sendButton.setText("Send");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(sendButton, gbc);
        inputTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(inputTextField, gbc);
        usernameLabel = new JLabel();
        usernameLabel.setText("username:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(usernameLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
